### ISSUE TITLE
exinfos.ipynb中有个参数错误

### ISSUE THREAD

**Issue by hackdoors** [yhangf/DataCon#2]
作为一个初学者，很希望能够作者能够尽量多点解释或者至少不用自己修改代码。

**Comment by hackdoors** [comment]
![image](https://user-images.githubusercontent.com/48487393/192138103-62ae1e97-1b34-403d-95e8-177c63ab24d4.png)

**Comment by hackdoors** [comment]
由于我学习的思路是先将代码能够跑起来，然后再一步步调试琢磨作者的思路，但是在exinfos中遇到train参数报错，由于自己水平有限、也没有系统的学习过机器学习的知识，所以作者能否指点一下这个参数的意思并告知如何修改吗？

**Comment by yhangf** [comment]
你好，当前的问题不仅仅是跑不起来的问题，我觉得你思路反了，应该先学思路，后面再理解代码，而且你环境都没配置好，太多的问题了，现阶段可能我的指导意义不大，抱歉。
